apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app1-pod-1
    app: app1
    env: dev
  name: app1-pod-1
  namespace: app1-dev
spec:
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}