apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume-pod
spec:
  containers:               # Content agent container
  - image: luksa/fortune
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs   # Containers filesystem
  - image: nginx:alpine          # Web-server container
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}