apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume
spec:
  storageClassName: do-block-storage-retain
  capacity:
    storage: 25Gi
  csi:
    driver: dobs.csi.digitalocean.com      # provision
    volumeHandle: volume-nyc3-01
  accessModes: 
    - ReadWriteOnce
