apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3                       # How many pod that you would like to create
  selector:                         # Label selector
    app: nginx                      # label
  template:                         # Pod template, Pod specifications
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80